# **EXPERIMENT 5:** Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
## **NAME:** SWAPAN CHETRI 

In [1]:
# importing the required library
import numpy as np

In [9]:
# taking the input from the user
input_1=int(input("Enter the no of rows:: "))
input_2=int(input("Enter the no of columns:: "))
row=input_1-1
# creating a zeros matrix of 10x10
array=np.zeros((input_1,input_2))

Enter the no of rows:: 10
Enter the no of columns:: 10


In [10]:
# logic
for i in range(input_1):
  array[0][i]=1
  array[i][0]=1
  array[row][i]=1
  array[i][row]=1

In [11]:
# printing array
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [12]:
# method 2

In [23]:
# creating a ones matrix of 10x10
array_2=np.ones((input_1,input_2))

In [24]:
# logic
array_2[1:-1,1:-1]=0

In [22]:
# printing the array
array_2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])