# ***CLASSWORK: Import numpy and show different methods in it***

In [58]:
# importing numpy library
import numpy as np

In [2]:
# creating single dimensional array
np.array([10,50,60,70])

In [5]:
# creating array with zeroes
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# creating two single dimensional array
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
np.sum(a1)

10

In [11]:
# summation of two array
a1+a2

array([ 6,  8, 10, 12])

In [22]:
# creating a multi dimensional array
a3=np.array([[1,2,3,4],[6,7,8,9]])

In [24]:
# sum of array columnwise
a3.sum(axis=0)

array([ 7,  9, 11, 13])

In [25]:
# sum of array rowwise
a3.sum(axis=1)

array([10, 30])

In [28]:
# arange method to print number in a certain range
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [27]:
# linspace method
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [29]:
# checking shape if array
a3.shape

(2, 4)

In [35]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])

In [36]:
# creating vertical stack
np.vstack((a1,a2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
# creating horizontal stack
np.hstack((a1,a2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
# creating column stack
np.column_stack((a1,a2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [48]:
# finding mean of array 
np.mean(a1)

2.5

In [49]:
# finding standard deviation of array a1
np.std(a1)

1.118033988749895

In [50]:
# finding median of array a1
np.median(a1)

2.5

In [52]:
# saving and loading an array
np.save("first_array.npy",a1)

In [53]:
# loading the saved array
np.load("first_array.npy")

array([1, 2, 3, 4])

In [57]:
# converting array into a list
print("the type of a1 is",type(a1))
a3=list(a1)
print("after converting the type of a1 is",type(a3))

the type of a1 is <class 'numpy.ndarray'>
after converting the type of a1 is <class 'list'>


In [59]:
b=np.empty_like(a1)

In [60]:
b

array([4607182418800017408, 4611686018427387904, 4613937818241073152,
       4616189618054758400])

In [63]:
a1.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [64]:
a1.ravel()

array([1, 2, 3, 4])