# **EXPERIMENT 4:**  Write a NumPy program to convert a given array into a list and then convert it into a list again.

## **NAME:** SWAPAN CHETRI 

In [3]:
# importing the required library
import numpy as np

In [19]:
# creating a array using numpy
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
# printing the array
print(n1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# printting the type of a before converting it to list
type(n1)

numpy.ndarray

In [20]:
# changing array to list
l1=list(n1)
# checking the type of l1
type(l1)
# we have converted a array(n1) to a list(l1) 

list

In [18]:
# converting list to array
n2=np.array(l1)
# printing the type of n2
type(n2)

numpy.ndarray

In [17]:
# printing the value of n2
print(n2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
