# **EXPERIMENT 3:**  Write a NumPy program to create a 3x3x3 array filled with arbitrary values

## **NAME:** SWAPAN CHETRI 

In [3]:
# importing the numpy library
import numpy as np

In [4]:
# Creating a 3x3x3 array filled with arbitary values
n1=np.random.random((3,3,3))

In [5]:
# printing the matrix
print(n1)

[[[0.0339798  0.78184357 0.55092499]
  [0.42146874 0.63909731 0.46529993]
  [0.03009045 0.34442905 0.48609508]]

 [[0.41810194 0.88896024 0.65921082]
  [0.30877252 0.12586585 0.83089726]
  [0.72687726 0.19907644 0.77350715]]

 [[0.97010511 0.70526311 0.8016338 ]
  [0.87134095 0.28766014 0.42512603]
  [0.38053337 0.48043141 0.24416995]]]


In [6]:
# printing the type of n1
type(n1)

numpy.ndarray